filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
          match_source: true

processors:
  - drop_fields:
      fields: ["agent", "ecs", "input", "host"]
      ignore_missing: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: warning
