// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkOrderService.Infrastructure;

#nullable disable

namespace WorkOrderService.Infrastructure.Migrations
{
    [DbContext(typeof(WorkOrderDbContext))]
    partial class WorkOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkOrderService.Domain.LaborEntry", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("currency");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("description");

                b.Property<long>("HourlyRateCents")
                    .HasColumnType("bigint")
                    .HasColumnName("hourly_rate_cents");

                b.Property<decimal>("Hours")
                    .HasPrecision(10, 2)
                    .HasColumnType("numeric(10,2)")
                    .HasColumnName("hours");

                b.Property<string>("MechanicName")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("mechanic_name");

                b.Property<long>("TotalCents")
                    .HasColumnType("bigint")
                    .HasColumnName("total_cents");

                b.Property<Guid>("WorkOrderId")
                    .HasColumnType("uuid")
                    .HasColumnName("work_order_id");

                b.HasKey("Id");

                b.HasIndex("WorkOrderId")
                    .HasDatabaseName("ix_labor_entries_work_order_id");

                b.ToTable("labor_entries");
            });

            modelBuilder.Entity("WorkOrderService.Domain.WorkOrder", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<long>("ActualTotalCents")
                    .HasColumnType("bigint")
                    .HasColumnName("actual_total_cents");

                b.Property<string>("AssignedMechanic")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("assigned_mechanic");

                b.Property<DateTime?>("CompletedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("completed_at");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("currency");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uuid")
                    .HasColumnName("customer_id");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)")
                    .HasColumnName("description");

                b.Property<long>("EstimatedTotalCents")
                    .HasColumnType("bigint")
                    .HasColumnName("estimated_total_cents");

                b.Property<string>("Notes")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)")
                    .HasColumnName("notes");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("status");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<Guid>("VehicleId")
                    .HasColumnType("uuid")
                    .HasColumnName("vehicle_id");

                b.HasKey("Id");

                b.HasIndex("CustomerId")
                    .HasDatabaseName("ix_work_orders_customer_id");

                b.HasIndex("Status")
                    .HasDatabaseName("ix_work_orders_status");

                b.HasIndex("CustomerId", "Status")
                    .HasDatabaseName("ix_work_orders_customer_id_status");

                b.ToTable("work_orders");
            });

            modelBuilder.Entity("WorkOrderService.Domain.WorkOrderLineItem", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("currency");

                b.Property<Guid>("PartId")
                    .HasColumnType("uuid")
                    .HasColumnName("part_id");

                b.Property<string>("PartName")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("part_name");

                b.Property<long>("TotalPriceCents")
                    .HasColumnType("bigint")
                    .HasColumnName("total_price_cents");

                b.Property<long>("UnitPriceCents")
                    .HasColumnType("bigint")
                    .HasColumnName("unit_price_cents");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<Guid>("WorkOrderId")
                    .HasColumnType("uuid")
                    .HasColumnName("work_order_id");

                b.HasKey("Id");

                b.HasIndex("PartId")
                    .HasDatabaseName("ix_work_order_line_items_part_id");

                b.HasIndex("WorkOrderId")
                    .HasDatabaseName("ix_work_order_line_items_work_order_id");

                b.ToTable("work_order_line_items");
            });

            modelBuilder.Entity("WorkOrderService.Domain.LaborEntry", b =>
            {
                b.HasOne("WorkOrderService.Domain.WorkOrder", "WorkOrder")
                    .WithMany("LaborEntries")
                    .HasForeignKey("WorkOrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("WorkOrder");
            });

            modelBuilder.Entity("WorkOrderService.Domain.WorkOrderLineItem", b =>
            {
                b.HasOne("WorkOrderService.Domain.WorkOrder", "WorkOrder")
                    .WithMany("LineItems")
                    .HasForeignKey("WorkOrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("WorkOrder");
            });

            modelBuilder.Entity("WorkOrderService.Domain.WorkOrder", b =>
            {
                b.Navigation("LaborEntries");
                b.Navigation("LineItems");
            });
#pragma warning restore 612, 618
        }
    }
}
